version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: apigo-sample
    volumes:
      - ./data:/var/lib/postgres/data
    ports:
      - "9000:5432"
    environment:
      POSTGRES_DB: apigo-sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    restart: always